language: node_js
node_js:
  - 10
  - 12
  - 14
addons:
  code_climate:
    repo_token: "$CODE_CLIMATE_TOKEN"
install:
  - yarn
  - yarn global add mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
before_script:
  - yarn run eslint
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
jobs:
  include:
  - stage: yarn publish
    if: tag IS present
    script: skip
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_API_KEY"
      on:
        tags: true
        repo: eexit/ghost-storage-cloudinary
